### ISSUE TITLE
黑名单无法正常工作

### ISSUE THREAD

**Issue by studioprintf** [ihacklog/p4davan#2]
描述：
刷好固件一开始正常工作，拉黑的人确实不能正常上网了（能连上wifi但无网络服务），昨晚想把拉黑的人取消的时候，在页面取消拉黑成功，但仍然无法上网。
测试 1：
将自己的手机拉黑（确认IP和MAC地址都为自己的手机），等待5分钟之后仍然可以上网。
测试 2：
拉黑自己手机之后，将原有在黑名单中的设备取消拉黑，5分钟后仍然没有生效，重启路由器之后，发现黑名单还原到修改之前。（反复测试了3次）
环境：
TOTOLINK A3004NS padavan 3.4.3.9-099_20170624-1443
PPPOE拨号上网，开启Aria KMS 其余插件关闭 其他系统设置保持默认

**Comment by studioprintf** [comment]
需要补充的是恢复出厂设置之后，黑名单仍然不能正常工作

**Comment by ihacklog** [comment]
其实这个问题不只你一个人提过说这是bug.
但是实际上block功能工作得很好。
那么问题来了，为什么在你那里不能工作？
原因只有一种，你开了koolproxy或 adbyby插件，或者自己设置了iptables相关的规则。
为了验证你说的问题，我今天特意测试了一次。

**Comment by ihacklog** [comment]
验证block 能否正常工作 的最简单的方法是开个app ：
`ping www.163.com`

**Comment by studioprintf** [comment]
我没有打开koolproxy或adbyby插件，因为我本人不喜欢用这些插件
iptables我没有进行过修改
![default](https://user-images.githubusercontent.com/13327564/27617826-54805398-5beb-11e7-8b4b-ce6aca24584e.PNG)
附带日志文件（日志文件中确实有koolproxy的字样，但应该不是启动
[syslog.txt](https://github.com/ihacklog/p4davan/files/1107384/syslog.txt)
）

**Comment by ihacklog** [comment]
从你的表看，你并没有添加任何过滤。

**Comment by ihacklog** [comment]
还有，结论我这里已经测试出来了。黑名单功能没有发现不工作的地方。一切正常。
如果你不相信我也没有办法。

**Comment by ihacklog** [comment]
等你哪一天自己会用这个功能了，你就会发现我说的是对的。
现在你也不要冲突，不要急于否定别人的结束。
你报的这个问题我不是第一次听说。
在你之前有很多个人说这个不工作。没有一次是真的。

**Comment by studioprintf** [comment]
我查了下资料，padavan应该是使用iptables实现黑名单功能的吧？我的iptables没有封禁任何mac地址吧，但是我的web页面的黑名单列表里面是存在一个黑名单的。

**Comment by studioprintf** [comment]
既然你都这么确定了，那就是我不会用吧。
