### ISSUE TITLE
外网不能登出

### ISSUE THREAD

**Issue by zhuwenbing** [ihacklog/p4davan#3]
硬件信息：
设备厂商：phicomm
设备具体型号(如psg1218-k2)：k2p
设备硬件版本(如A1))：A2
固件版本：3.4.3.9-099_20171116-0125

bug 详情描述：
已将路由器映射到外网，并通过域名+8443端口访问，登出的时候提示401 unauthorized

bug 重现具体步骤：
通过ddns将路由器映射到外网并绑定到域名8443端口上

预期的操作结果：
登出后再访问路由器需要重新登录

实际的操作结果：
登出后不用重新登录也可访问路由器

**Comment by zhuwenbing** [comment]
麻烦大神有空的时候帮忙看下，谢谢

**Comment by zhuwenbing** [comment]
问题移至[此处](https://github.com/ihacklog/p4davan-fw/issues/164)，手动关闭

**Comment by ihacklog** [comment]
这不是问题。这是功能。
http basic 认证的机制，建议你去了解一下。
